### ISSUE TITLE
Non-Rap

### ISSUE THREAD

**Issue by zombodotcom** [robbiebarrat/rapping-neural-network#14]
Could this be made to make non rap style lyrics? like say every rage against the machine lyrics were put in, would it turn into rap style lyrics?

**Comment by robbiebarrat** [comment]
You'd have to retrain it - it works with a basic rap flow because of the concentration on rhyme and syllables as opposed to actual singing, where different notes are sung and words are stretched out...

You could certainly try - I think it'd be neat to hear. Someone actually loaded it with Shakespeare and got decent results; https://www.youtube.com/watch?v=f1C3hRplR14
